import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sansCodeFont = localFont({
  src: "./fonts/sans-code/GoogleSansCode-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "Tatuka Engine",
  description: "Generated by Tsotne Darjania",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sansCodeFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
