import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sansCodeFont = localFont({
  src: "./fonts/sans-code/GoogleSansCode-VariableFont_wght.ttf",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Pixi Game Engine",
  description: "Generated by Tsotne Darjania",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(sansCodeFont.className);
  return (
    <html lang="en">
      <body className={`${sansCodeFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
